import type { Metadata } from 'next'
import styles from '../styles/Layout.module.css'
import { Footer } from '@/components/Footer'
import { Navbar } from '@/components/Navbar'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={styles.container}>
        <body className={styles.container}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
